---
stages:
  - shellcheck
  - test
  - docker-build
  - docker-push

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  # https://gitlab.com/gitlab-org/gitlab-ce/issues/64959
  # 19.03 had some breaking changes compared to 18.09
  DOCKER_TLS_CERTDIR: ""

shellcheck:
  stage: shellcheck
  image: qwe1/shellcheck
  script:
    - shellcheck -e SC2144 -Cauto -s bash dilbert.sh

test_download_debian:
  stage: test
  image: debian:buster-slim
  script:
    # reqs
    - bash -x docker/debian_pkg_req
    - bash -x dilbert.sh -t

docker-build:
  stage: docker-build
  image: docker:stable
  services:
    - docker:dind
  script:
    # https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
    - docker build -f docker/Dockerfile -t $CI_COMMIT_SHORT_SHA:$CI_COMMIT_SHA .
    - docker images

push_to_dockerhub:
 stage: docker-push
 image: docker:stable
 services:
   - docker:dind
 only:
   - master
 script:
   - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin
   - docker build -f docker/Dockerfile -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:latest -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$CI_COMMIT_SHA -t $CI_REGISTRY_IMAGE:latest -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA .
   - docker images
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:latest
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$CI_COMMIT_SHA
   - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
   - docker push $CI_REGISTRY_IMAGE:latest
   - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
