---
stages:
  - shellcheck
  - test

shellcheck:
  stage: shellcheck
  image: qwe1/shellcheck
  script:
    - shellcheck -e SC2144 -Cauto -s bash dilbert.sh

test_download:
  stage: test
  image: debian:buster-slim
  script:
    # reqs
    - bash -x debian_pkg_req
    - bash -x dilbert.sh -t
