---
stages:
  - shellcheck
  - test

shellcheck:
  stage: shellcheck
  image: qwe1/shellcheck
  script:
    - shellcheck -e SC2144 -Cauto -s bash dilbert.sh

test_download_debian:
  stage: test
  image: debian:buster-slim
  script:
    # reqs
    - bash -x debian_pkg_req
    - bash -x dilbert.sh -t

test_download_ubuntu:
  stage: test
  image: ubuntu:18.04
  script:
    # reqs
    - bash -x debian_pkg_req
    - bash -x dilbert.sh -t

test_download_fedora:
  stage: test
  image: fedora:latest
  script:
    # reqs
    - bash -x redhat_pkg_req
    - bash -x dilbert.sh -t

test_download_c7:
  stage: test
  image: centos:7
  script:
    # reqs
    - bash -x redhat_pkg_req
    - bash -x dilbert.sh -t

test_download_c8:
  stage: test
  image: centos:8
  script:
    # reqs
    - bash -x redhat_pkg_req
    - bash -x dilbert.sh -t